# Generated by Django 3.2.9 on 2022-09-01 18:05

from django.db import migrations, models
import django.db.models.deletion
import ingles.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0014_auto_20220309_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagocurso',
            field=models.FileField(blank=True, null=True, upload_to=ingles.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagomaterial',
            field=models.FileField(blank=True, null=True, upload_to=ingles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(blank=True, db_column='Estado', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='idestado',
            field=models.ForeignKey(blank=True, db_column='idestado', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.estado'),
        ),
    ]
