# Generated by Django 3.2.9 on 2022-09-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0015_auto_20220901_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='pagocurso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='pagomaterial',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='det_grupo',
            name='calif',
            field=models.CharField(blank=True, db_column='Calif', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='det_grupo',
            name='idestudiante',
            field=models.ForeignKey(blank=True, db_column='IdEstudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.estudiante'),
        ),
        migrations.AlterField(
            model_name='det_grupo',
            name='idgrupo',
            field=models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.grupo'),
        ),
        migrations.AlterField(
            model_name='det_grupo',
            name='idperiodo',
            field=models.ForeignKey(blank=True, db_column='IdPeriodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.periodo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechapago',
            field=models.DateField(db_column='FechaPago', null=True),
        ),
    ]
