# Generated by Django 3.2.9 on 2022-09-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0016_auto_20220925_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Facilitador', 'verbose_name_plural': 'Facilitadores'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Cuso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='idgrupo',
            field=models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.grupo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidom',
            field=models.CharField(blank=True, db_column='ApellidoM', default=' ', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nocontrol',
            field=models.IntegerField(blank=True, db_column='NoControl', default=' ', null=True),
        ),
    ]
