# Generated by Django 3.2.9 on 2022-09-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0017_auto_20220930_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pagomaterial',
        ),
    ]
