# Generated by Django 3.2.9 on 2022-10-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0018_remove_pago_pagomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_grupo',
            name='foliopago',
            field=models.ForeignKey(blank=True, db_column='FolioPago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingles.pago'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nocontrol',
            field=models.IntegerField(blank=True, db_column='NoControl', null=True),
        ),
    ]
