# Generated by Django 3.2.9 on 2022-10-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0019_auto_20221003_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_grupo',
            name='foliopago',
            field=models.ForeignKey(blank=True, db_column='FolioPago', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.pago'),
        ),
    ]
