# Generated by Django 3.2.9 on 2022-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0020_alter_det_grupo_foliopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nocontrol',
            field=models.CharField(blank=True, db_column='NoControl', max_length=150, null=True),
        ),
    ]
