# Generated by Django 3.2.9 on 2022-11-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0021_alter_estudiante_nocontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='idgrupo',
            field=models.ForeignKey(db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingles.grupo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.CharField(blank=True, db_column='Monto', max_length=25, null=True),
        ),
    ]
