# Generated by Django 3.2.9 on 2023-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0023_grupo_estadog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='estadoG',
        ),
        migrations.AddField(
            model_name='grupo',
            name='capacidad',
            field=models.IntegerField(blank=True, db_column='Capacidad', default=25, null=True),
        ),
    ]
