# Generated by Django 3.2.9 on 2023-01-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0025_grupo_estadog'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cursando',
            field=models.BooleanField(default=False, verbose_name='Cursando'),
        ),
    ]
