# Generated by Django 3.2.9 on 2023-01-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0026_estudiante_cursando'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], db_column='Grupo', default='A', max_length=5, null=True),
        ),
    ]
