# Generated by Django 3.2.9 on 2023-01-26 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingles', '0027_grupo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='ced',
            field=models.CharField(blank=True, db_column='Cedula', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, db_column='Correo Electrónico', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, db_column='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='rfc',
            field=models.CharField(blank=True, db_column='RFC', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
