# Generated by Django 3.2.9 on 2023-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingles', '0028_auto_20230126_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], db_column='Grupo', default='A', max_length=5, null=True),
        ),
    ]
